name: PrivateServer
version: "0.9"
main: de.luuuuuis.privateserver.spigot.PrivateServer
author: Luuuuuis
depends:
  - CloudNetAPI
description: Start private servers for CloudNet 2
website: https://github.com/Luuuuuis/PrivateServer
