name: PrivateServer
version: "0.7.1"
main: de.luuuuuis.privateserver.spigot.PrivateServer
author: Luuuuuis
depends:
  - CloudNetAPI
description: Start private servers for cloudnet 2.0
website: https://github.com/Luuuuuis/PrivateServer
