name: Discord Update

on:
  release:
    types:
      - created
jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          file: "https://github.com/Luuuuuis/PrivateServer/releases/latest/download/PrivateServer.jar"
          message: "An update for PrivateServer is avilable. Download now."
